<?php
define("SESSION_TTL", 15); // minutes
define("CRYPT_ROUNDS", 15);
define("MAX_AMOUNT_OF_TICKETS_PER_SEMESTER", 100);
define("REFERENCE_NUMBER_BASE", 1000);
define("TICKET_PRICE", 2);
define("TICKET_BASE_NUMBER_1", 100);
define("TICKET_BASE_NUMBER_2", 1000000);
