services:
  slim:
    class: Slim\Slim
  lounaslippu.repository.authentication:
    class: Lounaslippu\Repository\AuthenticationRepository
  lounaslippu.repository.user:
    class: Lounaslippu\Repository\UserRepository
  lounaslippu.repository.ticket:
      class: Lounaslippu\Repository\TicketRepository
  lounaslippu.repository.invoice:
      class: Lounaslippu\Repository\InvoiceRepository
  lounaslippu.repository.payment:
        class: Lounaslippu\Repository\PaymentRepository

  lounaslippu.service.authentication:
    class: Lounaslippu\Service\AuthenticationService
    arguments:
      - @lounaslippu.repository.authentication
  lounaslippu.service.registration:
    class: Lounaslippu\Service\RegistrationService
    arguments:
      - @lounaslippu.repository.authentication
      - @lounaslippu.repository.user
  lounaslippu.service.payment:
    class: Lounaslippu\Service\PaymentService
    arguments:
      - @lounaslippu.repository.payment
      - @lounaslippu.repository.invoice
  lounaslippu.service.ticket:
    class: Lounaslippu\Service\TicketService
    arguments:
      - @lounaslippu.repository.ticket
      - @lounaslippu.service.payment
  lounaslippu.service.payment.import:
    class: Lounaslippu\Service\PaymentImportService
    arguments:
      - @lounaslippu.repository.payment
  lounaslippu.service.user:
    class: Lounaslippu\Service\UserService
    arguments:
      - @lounaslippu.service.registration
      - @lounaslippu.repository.user
      - @lounaslippu.service.authentication



  lounaslippu.controller.login:
    class: Lounaslippu\Controller\LoginController
    arguments:
      - @lounaslippu.service.authentication
  lounaslippu.controller.front_page:
    class: Lounaslippu\Controller\FrontPageController
    arguments:
      - @lounaslippu.service.authentication
  lounaslippu.controller.registration:
    class: Lounaslippu\Controller\RegistrationController
    arguments:
      - @lounaslippu.service.registration
  lounaslippu.controller.ticket:
    class: Lounaslippu\Controller\TicketController
    arguments:
      - @lounaslippu.service.authentication
      - @lounaslippu.service.ticket
      - @lounaslippu.service.payment
  lounaslippu.controller.payment.import:
    class: Lounaslippu\Controller\PaymentImportController
    arguments:
      - @lounaslippu.service.authentication
      - @lounaslippu.service.payment.import
  lounaslippu.controller.user:
    class: Lounaslippu\Controller\UserController
    arguments:
      - @lounaslippu.service.authentication
      - @lounaslippu.service.user

  lounaslippu.api.controller.validator:
    class: Lounaslippu\Controller\ValidatorController
    arguments:
      - @slim
      - @lounaslippu.service.registration





