services:

  lounaslippu.repository.authentication:
    class: Lounaslippu\Repository\AuthenticationRepository

  lounaslippu.service.authentication:
    class: Lounaslippu\Service\AuthenticationService
    arguments:
      - @lounaslippu.repository.authentication

  lounaslippu.controller.test:
    class: Lounaslippu\Controller\TestController
  lounaslippu.controller.login:
    class: Lounaslippu\Controller\LoginController
    arguments:
          - @lounaslippu.service.authentication
  lounaslippu.controller.front_page:
    class: Lounaslippu\Controller\FrontPageController
    arguments:
          - @lounaslippu.service.authentication
  lounaslippu.controller.registration:
    class: Lounaslippu\Controller\RegistrationController





