-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS `log` CASCADE;
DROP TABLE IF EXISTS `ticket_import` CASCADE;
DROP TABLE IF EXISTS `permissions` CASCADE;
DROP TABLE IF EXISTS `user_roles` CASCADE;
DROP TABLE IF EXISTS `roles` CASCADE;
DROP TRIGGER IF EXISTS `payment_amount_left`;
DROP TABLE IF EXISTS `payment` CASCADE;
DROP TABLE IF EXISTS `ticket` CASCADE;
DROP TABLE IF EXISTS `invoice` CASCADE;
DROP TABLE IF EXISTS `users` CASCADE;