-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS "log" CASCADE;
DROP TABLE IF EXISTS "ticket_import" CASCADE;
DROP TABLE IF EXISTS "permissions" CASCADE;
DROP TABLE IF EXISTS "user_roles" CASCADE;
DROP TABLE IF EXISTS "roles" CASCADE;
DROP TABLE IF EXISTS "payment" CASCADE;
DROP TABLE IF EXISTS "ticket" CASCADE;
DROP TABLE IF EXISTS "invoice" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;

-- TRIGGERIT
DROP TRIGGER IF EXISTS update_user ON users CASCADE;

--FUNKTIOT
DROP FUNCTION IF EXISTS update_user_modified_column();